
#ifndef SDL_HINTS_CH_
#define SDL_HINTS_CH_

#define SDL_HINT_VIDEO_HIGHDPI_DISABLED "SDL_VIDEO_HIGHDPI_DISABLED"
#define SDL_HINT_VIDEO_X11_NET_WM_PING  "SDL_VIDEO_X11_NET_WM_PING"

#endif /* End SDL_HINTS_CH_ */
